# Generated by Django 4.2.1 on 2023-05-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='coordinator',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
